//createProduct
POST http://localhost:3003/product/create
Content-Type: application/json

{
  "name":"Cholate Nestle",
  "description":"Cholate ao leite 100g",
  "price": 5.50,
  "qtyInStock": 700
}

###
//findAllProducts
GET http://localhost:3003/product